preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  jetbrains-compose-dev:
    url: https://maven.pkg.jetbrains.space/public/p/compose/dev

plugins:
  org.jetbrains.kotlin.multiplatform:
    alias: kotlin-multiplatform
    version: +
  org.jetbrains.compose:
    alias: jetbrains-compose
    version: +
    repositories:
      maven-central
  com.android.application:
    alias: android-application
    version: +
  com.android.library:
    alias: android-library
    version-ref: android-application

libraries:
  # Use a placeholder for the alpha compose version
  # In the project to use "androidx.compose.android.version" to obtain the version
  # and use the "resolutionStrategy" to replace all the current "stable" versions
  androidx.compose.runtime:
    runtime-android:
      alias: androidx-compose-android
      version: ^1.6.0-alpha01
  androidx.activity:
    activity:
      version: +
    activity-compose:
      version: +
  androidx.core:
    core-ktx:
      version: +
  com.google.android.material:
    material:
      version: +
  androidx.test.ext:
    junit:
      version: +
  androidx.test.espresso:
    espresso-core:
      version: +
  junit:
    junit:
      version: +