preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  jetbrains-compose-dev:
    url: https://maven.pkg.jetbrains.space/public/p/compose/dev

plugins:
  org.jetbrains.kotlin.multiplatform:
    alias: kotlin-multiplatform
    # Manually update this version visit https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compatibility-and-versioning.html
    version: 1.9.21
  org.jetbrains.compose:
    alias: jetbrains-compose
    # Manually update this version visit https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compatibility-and-versioning.html
    version: 1.5.11
    repositories:
      maven-central
  com.android.application:
    alias: android-application
    version: +
  com.android.library:
    alias: android-library
    version-ref: android-application

libraries:
  com.highcapable.flexiui:
    core:
      version: +
      # Flexi UI is in alpha stage for now.
      version-filter:
        use-internal: false
  com.highcapable.betterandroid:
    ui-component:
      version: +
    ui-extension:
      version: +
    system-extension:
      version: +
    compose-extension:
      version: +
    compose-multiplatform:
      version: +
  androidx.activity:
    activity:
      version: +
    activity-compose:
      version: +
  androidx.core:
    core-ktx:
      version: +
  androidx.test.ext:
    junit:
      version: +
  androidx.test.espresso:
    espresso-core:
      version: +
  junit:
    junit:
      version: +